namespace: "my-namespace"

replicas: "3"

image:
  repository: my-aws-account-id.dkr.ecr.region.amazonaws.com/my-app
  tag: latest

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"