apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "migration.fullname" . }}
  labels:
    app: my-app
spec:
  type:  LoadBalancer # if you want to config this value {{ .Values.service.type }}
  ports:
    - port: 80 
      targetPort: 8080 #Port open in the app image
      protocol: TCP
      name: http
  selector:
    app: my-app
